name: dictionary
description: Mobile Challenge 2023 - Dictionary

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  get: ^4.6.6
  intl: ^0.18.0
  sqflite: ^2.3.0
  provider: ^6.0.5
  get_storage: ^2.1.1 
  cupertino_icons: ^1.0.2

  zezis_widget: ^0.0.3
  zezis_functions: ^0.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
